### ISSUE TITLE
Caravan module block spawing in overworld. Is normal?

### ISSUE THREAD

**Issue by vpontin** [4Space/4Space-1.7#31]
Hi!
New using 4Space (v 4.1.9, GC 1.7 v 3.0.12.350), and i found some wreid unbreakble blocks spawing in overworld.
After searching with creative and craftguide, i found this block are "Caravan Module", and is from 4space mercury addon.

Is a normal behavior for this block to generate in overworld. If yes, how i disable it (i cant found nothing in configs). If not, what i need to provide (logs, etc) to help solve this issue?

**Comment by mattparks** [comment]
Hi, can you provide what other mods you are using?

**Comment by mattparks** [comment]
I have decided that is is a mod conflict on a world that has existed and a new mod was loaded breaking a ore, try making a new world for fixing the conflict.

**Comment by vpontin** [comment]
Already dont generate it anymore. Never figured the circunstances of this unusual generation (maybe one of my 96 mods).

Sorry about this sh***ty ticket. Keep the good work :D
